### ISSUE TITLE
Missing required dependencies

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/Mouser#62]
I wanted to run this code on my Mac. I cloned the repo and ran `python3 main.py`, which resulted in the following error:
```
python3 main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from experiment_pages.select_experiment_ui import ExperimentsUI
  File "/Users/holdenerea/repos/Mouser/experiment_pages/select_experiment_ui.py", line 6, in <module>
    from experiment_pages.experiment_menu_ui import ExperimentMenuUI
  File "/Users/holdenerea/repos/Mouser/experiment_pages/experiment_menu_ui.py", line 6, in <module>
    from experiment_pages.map_rfid import MapRFIDPage
  File "/Users/holdenerea/repos/Mouser/experiment_pages/map_rfid.py", line 5, in <module>
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound'
```
Please add a requirements.txt file with a list of python libraries that are required for this project, to resolve this dependency issue.

**Comment by aithaprasad** [comment]
@kate-holdener Thank you for letting us know. @loganwyas please add all the discussed sound libraries into a requirements.txt and make sure we also mention the process in the readme file.
